import { wrapLanguageModel, ToolLoopAgent, InferAgentUIMessage, tool } from 'ai';
import { deepseek } from "@ai-sdk/deepseek";
import * as z from 'zod';
import { interfaceStructureDesignAgentInstructions, textAgentInstructions, interfaceStylingAgentInstructions, interfaceAlignmentCriticInstructions, interactionAgentInstructions } from './prompt';
import { outputSchemas } from './schema';
import { componentsMeta } from '../../../components/components-meta';

const supportedUiNames = componentsMeta.map(({ name }) => name) as [string, ...string[]];
const strictUiNeedSchema = z.enum(supportedUiNames);


const model = wrapLanguageModel({
  model: deepseek("deepseek-chat"),
  middleware: process.env.NODE_ENV === 'development'
    ? [(await import('@ai-sdk/devtools')).devToolsMiddleware()]
    : []
});

export const ShowResponseInput_Schema = z.object({
  text: z.string().describe("The text to be sent back to the boss."),
  topic: z.string().describe("The topic of the conversation."),
  necessary: z.boolean().describe("Whether the ui is necessary for the boss understanding."),
  uiDescription: z.string().describe("The description of the interface needed."),
  uiNeeds: z.array(strictUiNeedSchema).describe("A list of required business-intent components selected from supported metadata names."),
});

// admin agent
export const adminAgent = new ToolLoopAgent({
  model,
  instructions: textAgentInstructions,
  // output: outputSchemas.admin,
  tools: {
    // ...chatTools,
    // 'call-structure-agent(no stream)': callStructureAgent_Usual,
    // 'call-structure-agent(stream)': callStructureAgent_Stream,
    showResponse: tool({
      description: "Show the response to the user.",
      inputSchema: ShowResponseInput_Schema,
    })
  },
  toolChoice: 'required'
});
export type AdminAgentMessage = InferAgentUIMessage<typeof adminAgent>;

// structure agent
export const structureAgent = new ToolLoopAgent({
  model,
  output: outputSchemas.structure,
  callOptionsSchema: z.object({
    uiProvided: z.array(z.string()).describe('A list of UI components that are provided.')
  }),
  prepareCall: ({ options, ...settings }) => ({
    ...settings,
    instructions: `
      ${interfaceStructureDesignAgentInstructions}\n

      - The UI you can use:
      ${options.uiProvided?.join(", ") || "None"}

      - The schema of each UI component you should follow when designing the UI structure:
      ${componentsMeta.map(({ name, description, propsSchema, dslExample }) => `- ${name}: ${description}\nSchema:\n${JSON.stringify(propsSchema, null, 2)}\nExample:\n${JSON.stringify(dslExample, null, 2)}\n`).join("\n\n")}

      - Every node in uiTree MUST have a globally unique id, regardless of whether style stage will modify it.
      - Keep structure-stage classes minimal and layout-focused (spacing/layout/container only); leave visual polish (colors/gradients/shadows/state colors) to style stage.
      - After structuring the UI, provide a concise style summary for the style agent.
      `,
  }),
});

// style agent
export const styleAgent = new ToolLoopAgent({
  model,
  output: outputSchemas.style,
  instructions: "Check the UI tree provided to you, then using TailwindCss to design the styles those are exposed by className or classNames in the UI tree.",
  callOptionsSchema: z.object({
    uiTree: z.string().describe("The UI tree provided."),
    styleSummary: z.string().describe("A text summary of the style design suggestions for the entire UI."),
  }),
  prepareCall: ({ options, ...settings }) => ({
    ...settings,
    instructions: `
      ${interfaceStylingAgentInstructions}\n

      - The UI tree provided:
      ${options.uiTree || "None"}

      - The style summary provided by the structure agent for your reference:
      ${options.styleSummary || "None"}

      IMPORTANT: ${settings.instructions}
    `,
  }),
});

// alignment critic agent
export const alignmentAgent = new ToolLoopAgent({
  model,
  output: outputSchemas.alignment,
  callOptionsSchema: z.object({
    uiDescription: z.string().describe("The uiDescription from admin agent."),
    uiNeeds: z.array(z.string()).describe("Required UI component names selected by admin agent."),
    uiTree: z.string().describe("The UI tree generated by structure agent."),
  }),
  prepareCall: ({ options, ...settings }) => ({
    ...settings,
    instructions: `
      ${interfaceAlignmentCriticInstructions}

      - uiDescription:
      ${options.uiDescription || "None"}

      - uiNeeds:
      ${(options.uiNeeds ?? []).join(", ") || "None"}

      - uiTree:
      ${options.uiTree || "None"}

      - Supported components:
      ${componentsMeta.map(({ name }) => `- ${name}`).join("\n")}

      IMPORTANT:
      - If alignmentScore < 85, verdict must be "retry".
      - Keep retryPrompt short, specific and directly actionable.
    `,
  }),
});

export const interactionAgent = new ToolLoopAgent({
  model,
  output: outputSchemas.interaction,
  callOptionsSchema: z.object({
    interactionType: z.string().describe("The type of interaction triggered"),
    interactionDescription: z.string().describe("Description of what the interaction should produce"),
    currentPageContext: z.string().optional().describe("The current page UI tree for context"),
    uiProvided: z.array(z.string()).describe("Available UI component names"),
  }),
  prepareCall: ({ options, ...settings }) => ({
    ...settings,
    instructions: `
      ${interactionAgentInstructions}

      - The interaction type: ${options.interactionType}
      - The interaction description: ${options.interactionDescription}
      - Available UI components: ${options.uiProvided?.join(", ") || "None"}

      - The schema of each UI component:
      ${componentsMeta.map(({ name, description, propsSchema, dslExample }) => `- ${name}: ${description}\nSchema:\n${JSON.stringify(propsSchema, null, 2)}\nExample:\n${JSON.stringify(dslExample, null, 2)}\n`).join("\n\n")}

      - Current page context:
      ${options.currentPageContext || "None"}

      - Every node in uiTree MUST have a globally unique id.
      - For interactive elements, define interaction slots following the same rules as the structure agent.
    `,
  }),
});

export const styleEditAgent = new ToolLoopAgent({
  model,
  output: outputSchemas.styleEdit,
  callOptionsSchema: z.object({
    uiTreeSummary: z.string().describe("Summary of the current UI tree structure with node IDs and types"),
    currentStyles: z.string().describe("Current styles mapping (nodeId -> className)"),
    editRequest: z.string().describe("User's description of the style change they want"),
  }),
  prepareCall: ({ options, ...settings }) => ({
    ...settings,
    instructions: `
      You are a style editing agent. Your task is to make targeted style modifications to specific nodes in the UI tree.

      - Current UI tree structure:
      ${options.uiTreeSummary || "None"}

      - Current styles:
      ${options.currentStyles || "None"}

      - User's edit request:
      ${options.editRequest || "None"}

      Rules:
      - Only modify styles for nodes that are relevant to the user's request
      - Use valid Tailwind CSS utility classes
      - For "replace-class", provide the complete new className (it replaces the old one entirely)
      - For "add-class", provide only the additional classes to append
      - For "remove-class", provide the classes to remove from the existing className
      - Keep changes minimal and focused
    `,
  }),
});