import { wrapLanguageModel, ToolLoopAgent, InferAgentUIMessage } from 'ai';
import { deepseek } from "@ai-sdk/deepseek";
import { devToolsMiddleware } from '@ai-sdk/devtools';
import * as z from 'zod';
import { chatTools } from './tools';
import { interfaceStructureDesignAgentInstructions, textAgentInstructions, interfaceStylingAgentInstructions, interfaceAlignmentCriticInstructions } from './prompt';
import { outputSchemas } from './schema';
import { componentsMeta } from './components-meta';


const model = wrapLanguageModel({
  model: deepseek("deepseek-chat"),
  middleware: [
    devToolsMiddleware(),
  ]
});

// admin agent
export const adminAgent = new ToolLoopAgent({
  model,
  instructions: textAgentInstructions,
  output: outputSchemas.admin,
  tools: {
    ...chatTools,
    // 'call-structure-agent(no stream)': callStructureAgent_Usual,
    // 'call-structure-agent(stream)': callStructureAgent_Stream,
  },
  toolChoice: 'auto'
});
export type AdminAgentMessage = InferAgentUIMessage<typeof adminAgent>;

// structure agent
export const structureAgent = new ToolLoopAgent({
  model,
  output: outputSchemas.structure,
  callOptionsSchema: z.object({
    uiProvided: z.array(z.string()).describe('A list of UI components that are provided.')
  }),
  prepareCall: ({ options, ...settings }) => ({
    ...settings,
    instructions: `
      ${interfaceStructureDesignAgentInstructions}\n

      - The UI you can use:
      ${options.uiProvided?.join(", ") || "None"}

      - The schema of each UI component you should follow when designing the UI structure:
      ${componentsMeta.map(({ name, description, propsSchema, dslExample }) => `- ${name}: ${description}\nSchema:\n${JSON.stringify(propsSchema, null, 2)}\nExample:\n${JSON.stringify(dslExample, null, 2)}\n`).join("\n\n")}

      - Every node in uiTree MUST have a globally unique id, regardless of whether style stage will modify it.
      - Keep structure-stage classes minimal and layout-focused (spacing/layout/container only); leave visual polish (colors/gradients/shadows/state colors) to style stage.
      - After structuring the UI, provide a concise style summary for the style agent.
      `,
  }),
});

// style agent
export const styleAgent = new ToolLoopAgent({
  model,
  output: outputSchemas.style,
  instructions: "Check the UI tree provided to you, then using TailwindCss to design the styles those are exposed by className or classNames in the UI tree.",
  callOptionsSchema: z.object({
    uiTree: z.string().describe("The UI tree provided."),
    styleSummary: z.string().describe("A text summary of the style design suggestions for the entire UI."),
  }),
  prepareCall: ({ options, ...settings }) => ({
    ...settings,
    instructions: `
      ${interfaceStylingAgentInstructions}\n

      - The UI tree provided:
      ${options.uiTree || "None"}

      - The style summary provided by the structure agent for your reference:
      ${options.styleSummary || "None"}

      IMPORTANT: ${settings.instructions}
    `,
  }),
});

// alignment critic agent
export const alignmentAgent = new ToolLoopAgent({
  model,
  output: outputSchemas.alignment,
  callOptionsSchema: z.object({
    uiDescription: z.string().describe("The uiDescription from admin agent."),
    uiNeeds: z.array(z.string()).describe("Required UI component names selected by admin agent."),
    uiTree: z.string().describe("The UI tree generated by structure agent."),
  }),
  prepareCall: ({ options, ...settings }) => ({
    ...settings,
    instructions: `
      ${interfaceAlignmentCriticInstructions}

      - uiDescription:
      ${options.uiDescription || "None"}

      - uiNeeds:
      ${(options.uiNeeds ?? []).join(", ") || "None"}

      - uiTree:
      ${options.uiTree || "None"}

      - Supported components:
      ${componentsMeta.map(({ name }) => `- ${name}`).join("\n")}

      IMPORTANT:
      - If alignmentScore < 85, verdict must be "retry".
      - Keep retryPrompt short, specific and directly actionable.
    `,
  }),
});